In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split

In [2]:
import sys
import os

sys.path.append(os.path.abspath(".."))
sys.path.append(os.path.abspath("../.."))

In [3]:
BASE_DIR = Path.cwd().parents[1]
RAW_DATA_PATH = BASE_DIR / "Data" / "SCAN" / "raw" / "SCAN_ames_all.csv"
PROCESSED_DIR = BASE_DIR / "Data" / "SCAN" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("BASE_DIR:", BASE_DIR)
print("RAW_DATA_PATH exists:", RAW_DATA_PATH.exists())
print("PROCESSED_DIR:", PROCESSED_DIR)

BASE_DIR: /Users/m.mughees/Desktop/Pi-515-2026
RAW_DATA_PATH exists: True
PROCESSED_DIR: /Users/m.mughees/Desktop/Pi-515-2026/Data/SCAN/processed

In [4]:
scan_df = pd.read_csv(RAW_DATA_PATH, comment="#")
scan_df.head()

,Date,Ames (2031) Precipitation Accumulation (in),Ames (2031) Precipitation Increment (in),Ames (2031) Air Temperature Average (degF),Ames (2031) Air Temperature Maximum (degF),Ames (2031) Air Temperature Minimum (degF),Ames (2031) Air Temperature Observed (degF),Ames (2031) Soil Moisture Percent -2in (pct),Ames (2031) Soil Moisture Percent -4in (pct),Ames (2031) Soil Moisture Percent -8in (pct),...,Ames (2031) Salinity -8in (gram/l),Ames (2031) Salinity -20in (gram/l),Ames (2031) Salinity -40in (gram/l),Ames (2031) Solar Radiation Average (watt/m2),Ames (2031) Solar Radiation/langley Total (langley),Ames (2031) Vapor Pressure - Partial (inch_Hg),Ames (2031) Vapor Pressure - Saturated (inch_Hg),Ames (2031) Wind Direction Average (degree),Ames (2031) Wind Speed Average (mph),Ames (2031) Wind Speed Maximum (mph)
0,2001-09-23 09:00,NaN,NaN,55.2,58.1,54.1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,120.63,NaN,NaN,NaN,346.0,15.0,23.4
1,2001-09-23 10:00,0.0,NaN,56.7,57.6,55.0,55.0,20.4,40.6,41.3,...,0.4,0.6,0.4,209.04,NaN,NaN,NaN,358.0,16.9,24.0
2,2001-09-23 11:00,0.0,NaN,56.8,59.2,55.9,57.0,20.5,40.6,41.9,...,0.4,0.6,0.4,182.42,NaN,NaN,NaN,354.0,16.4,26.5
3,2001-09-23 12:00,0.0,NaN,56.5,57.2,55.8,56.5,20.4,40.6,41.9,...,0.4,0.6,0.5,131.38,NaN,NaN,NaN,358.0,15.7,23.9
4,2001-09-23 13:00,0.0,NaN,56.8,57.9,56.1,56.3,20.5,40.6,41.9,...,0.4,0.6,0.5,119.17,NaN,NaN,NaN,361.0,15.5,23.2

In [5]:
print(scan_df.columns.tolist())
print(scan_df.shape)

['Date', 'Ames (2031) Precipitation Accumulation (in)', 'Ames (2031) Precipitation Increment (in)', 'Ames (2031) Air Temperature Average (degF)', 'Ames (2031) Air Temperature Maximum (degF)', 'Ames (2031) Air Temperature Minimum (degF)', 'Ames (2031) Air Temperature Observed (degF)', 'Ames (2031) Soil Moisture Percent -2in (pct)', 'Ames (2031) Soil Moisture Percent -4in (pct)', 'Ames (2031) Soil Moisture Percent -8in (pct)', 'Ames (2031) Soil Moisture Percent -20in (pct)', 'Ames (2031) Soil Moisture Percent -40in (pct)', 'Ames (2031) Soil Temperature Observed -2in (degF)', 'Ames (2031) Soil Temperature Observed -4in (degF)', 'Ames (2031) Soil Temperature Observed -8in (degF)', 'Ames (2031) Soil Temperature Observed -20in (degF)', 'Ames (2031) Soil Temperature Observed -40in (degF)', 'Ames (2031) Battery (volt)', 'Ames (2031) Dew Point Temperature (degF)', 'Ames (2031) Real Dielectric Constant -2in (unitless)', 'Ames (2031) Real Dielectric Constant -4in (unitless)', 'Ames (2031) Real Dielectric Constant -8in (unitless)', 'Ames (2031) Real Dielectric Constant -20in (unitless)', 'Ames (2031) Real Dielectric Constant -40in (unitless)', 'Ames (2031) Relative Humidity Enclosure (pct)', 'Ames (2031) Relative Humidity Maximum (pct)', 'Ames (2031) Relative Humidity Minimum (pct)', 'Ames (2031) Salinity -2in (gram/l)', 'Ames (2031) Salinity -4in (gram/l)', 'Ames (2031) Salinity -8in (gram/l)', 'Ames (2031) Salinity -20in (gram/l)', 'Ames (2031) Salinity -40in (gram/l)', 'Ames (2031) Solar Radiation Average (watt/m2)', 'Ames (2031) Solar Radiation/langley Total (langley)', 'Ames (2031) Vapor Pressure - Partial (inch_Hg)', 'Ames (2031) Vapor Pressure - Saturated (inch_Hg)', 'Ames (2031) Wind Direction Average (degree)', 'Ames (2031) Wind Speed Average (mph)', 'Ames (2031) Wind Speed Maximum (mph)']
(205566, 39)

In [6]:
selected_columns = {
    "Date": "date",
    "Ames (2031) Precipitation Increment (in)": "total_precipitation",
    "Ames (2031) Air Temperature Average (degF)": "air_temperature",
    "Ames (2031) Dew Point Temperature (degF)": "dewpoint_temperature",
    "Ames (2031) Soil Moisture Percent -2in (pct)": "soil_moisture",
    "Ames (2031) Soil Temperature Observed -2in (degF)": "soil_temperature",
}

In [7]:
scan_df = scan_df[list(selected_columns.keys())].rename(columns=selected_columns)
scan_df.head()

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature
0,2001-09-23 09:00,NaN,55.2,NaN,NaN,NaN
1,2001-09-23 10:00,NaN,56.7,NaN,20.4,59.0
2,2001-09-23 11:00,NaN,56.8,NaN,20.5,59.0
3,2001-09-23 12:00,NaN,56.5,NaN,20.4,59.0
4,2001-09-23 13:00,NaN,56.8,NaN,20.5,60.0

In [8]:
scan_df = scan_df.replace(r"^\s*$", np.nan, regex=True)
scan_df = scan_df.dropna()

print(scan_df.shape)
scan_df.head()

(106353, 6)

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature
76946,2010-10-12 08:00,0.0,62.8,50.0,28.0,55.0
76947,2010-10-12 09:00,0.0,68.7,50.0,28.0,56.0
76948,2010-10-12 10:00,0.0,73.4,50.0,28.2,58.0
76949,2010-10-12 11:00,0.0,77.2,50.0,28.0,59.0
76950,2010-10-12 12:00,0.0,79.5,49.0,28.0,59.0

In [9]:
scan_df["date"] = pd.to_datetime(scan_df["date"])

numeric_cols = [
    "total_precipitation",
    "air_temperature",
    "dewpoint_temperature",
    "soil_moisture",
    "soil_temperature",
]

for col in numeric_cols:
    scan_df[col] = pd.to_numeric(scan_df[col], errors="coerce")

scan_df = scan_df.dropna()

scan_df.dtypes

date                    datetime64[ns]
total_precipitation            float64
air_temperature                float64
dewpoint_temperature           float64
soil_moisture                  float64
soil_temperature               float64
dtype: object

In [10]:
# Fahrenheit -> Celsius
scan_df["air_temperature"] = (scan_df["air_temperature"] - 32) * 5 / 9
scan_df["dewpoint_temperature"] = (scan_df["dewpoint_temperature"] - 32) * 5 / 9
scan_df["soil_temperature"] = (scan_df["soil_temperature"] - 32) * 5 / 9

# percent -> proportion
scan_df["soil_moisture"] = scan_df["soil_moisture"] / 100

scan_df.head()

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature
76946,2010-10-12 08:00:00,0.0,17.111111,10.000000,0.280,12.777778
76947,2010-10-12 09:00:00,0.0,20.388889,10.000000,0.280,13.333333
76948,2010-10-12 10:00:00,0.0,23.000000,10.000000,0.282,14.444444
76949,2010-10-12 11:00:00,0.0,25.111111,10.000000,0.280,15.000000
76950,2010-10-12 12:00:00,0.0,26.388889,9.444444,0.280,15.000000

In [11]:
scan_df["year"] = scan_df["date"].dt.year
scan_df["month"] = scan_df["date"].dt.month
scan_df["day"] = scan_df["date"].dt.day

scan_df.head()

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature,year,month,day
76946,2010-10-12 08:00:00,0.0,17.111111,10.000000,0.280,12.777778,2010,10,12
76947,2010-10-12 09:00:00,0.0,20.388889,10.000000,0.280,13.333333,2010,10,12
76948,2010-10-12 10:00:00,0.0,23.000000,10.000000,0.282,14.444444,2010,10,12
76949,2010-10-12 11:00:00,0.0,25.111111,10.000000,0.280,15.000000,2010,10,12
76950,2010-10-12 12:00:00,0.0,26.388889,9.444444,0.280,15.000000,2010,10,12

In [12]:
scan_df["latitude"] = 42.0347
scan_df["longitude"] = -93.62

scan_df.head()

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature,year,month,day,latitude,longitude
76946,2010-10-12 08:00:00,0.0,17.111111,10.000000,0.280,12.777778,2010,10,12,42.0347,-93.62
76947,2010-10-12 09:00:00,0.0,20.388889,10.000000,0.280,13.333333,2010,10,12,42.0347,-93.62
76948,2010-10-12 10:00:00,0.0,23.000000,10.000000,0.282,14.444444,2010,10,12,42.0347,-93.62
76949,2010-10-12 11:00:00,0.0,25.111111,10.000000,0.280,15.000000,2010,10,12,42.0347,-93.62
76950,2010-10-12 12:00:00,0.0,26.388889,9.444444,0.280,15.000000,2010,10,12,42.0347,-93.62

In [13]:
daily_scan_df = (
    scan_df.set_index("date")
    .resample("D")
    .agg({
        "total_precipitation": "sum",
        "air_temperature": "mean",
        "dewpoint_temperature": "mean",
        "soil_moisture": "mean",
        "soil_temperature": "mean",
        "year": "first",
        "month": "first",
        "day": "first",
        "latitude": "first",
        "longitude": "first",
    })
    .reset_index()
)

daily_scan_df.head()

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature,year,month,day,latitude,longitude
0,2010-10-12,0.0,19.711806,8.993056,0.281500,14.895833,2010.0,10.0,12.0,42.0347,-93.62
1,2010-10-13,0.0,12.039352,-0.972222,0.278250,12.615741,2010.0,10.0,13.0,42.0347,-93.62
2,2010-10-14,0.0,12.372685,-0.393519,0.275208,11.250000,2010.0,10.0,14.0,42.0347,-93.62
3,2010-10-15,0.0,10.773148,1.273148,0.272708,11.018519,2010.0,10.0,15.0,42.0347,-93.62
4,2010-10-16,0.0,13.719907,2.337963,0.272333,11.712963,2010.0,10.0,16.0,42.0347,-93.62

In [14]:
final_scan_df = daily_scan_df.copy()

In [15]:
final_scan_df["source"] = "SCAN"
final_scan_df.head()

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature,year,month,day,latitude,longitude,source
0,2010-10-12,0.0,19.711806,8.993056,0.281500,14.895833,2010.0,10.0,12.0,42.0347,-93.62,SCAN
1,2010-10-13,0.0,12.039352,-0.972222,0.278250,12.615741,2010.0,10.0,13.0,42.0347,-93.62,SCAN
2,2010-10-14,0.0,12.372685,-0.393519,0.275208,11.250000,2010.0,10.0,14.0,42.0347,-93.62,SCAN
3,2010-10-15,0.0,10.773148,1.273148,0.272708,11.018519,2010.0,10.0,15.0,42.0347,-93.62,SCAN
4,2010-10-16,0.0,13.719907,2.337963,0.272333,11.712963,2010.0,10.0,16.0,42.0347,-93.62,SCAN

In [16]:
from sklearn.preprocessing import StandardScaler
import joblib

feature_cols_to_scale = [
    "latitude",
    "longitude",
    "air_temperature",
    "dewpoint_temperature",
    "total_precipitation",
    "year",
    "month",
    "day",
]

scan_scaler = StandardScaler()
final_scan_df[feature_cols_to_scale] = scan_scaler.fit_transform(
    final_scan_df[feature_cols_to_scale]
)

MODEL_DIR = BASE_DIR / "src" / "models"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

joblib.dump(scan_scaler, MODEL_DIR / "scan_feature_scaler.joblib")

print("✅ Standardized SCAN numeric features")
print("✅ Saved SCAN scaler to:", MODEL_DIR / "scan_feature_scaler.joblib")

final_scan_df.head()

✅ Standardized SCAN numeric features
✅ Saved SCAN scaler to: /Users/m.mughees/Desktop/Pi-515-2026/src/models/scan_feature_scaler.joblib

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature,year,month,day,latitude,longitude,source
0,2010-10-12,-0.289215,0.880948,0.370174,0.281500,14.895833,-2.096143,0.989835,-0.428256,7.105427e-15,0.0,SCAN
1,2010-10-13,-0.289215,0.220629,-0.520759,0.278250,12.615741,-2.096143,0.989835,-0.314597,7.105427e-15,0.0,SCAN
2,2010-10-14,-0.289215,0.249317,-0.469021,0.275208,11.250000,-2.096143,0.989835,-0.200937,7.105427e-15,0.0,SCAN
3,2010-10-15,-0.289215,0.111656,-0.320015,0.272708,11.018519,-2.096143,0.989835,-0.087277,7.105427e-15,0.0,SCAN
4,2010-10-16,-0.289215,0.365264,-0.224816,0.272333,11.712963,-2.096143,0.989835,0.026382,7.105427e-15,0.0,SCAN

In [18]:
final_scan_df[feature_cols_to_scale].describe()

,latitude,longitude,air_temperature,dewpoint_temperature,total_precipitation,year,month,day
count,4.515000e+03,4515.0,4.515000e+03,4.515000e+03,5.361000e+03,4.515000e+03,4.515000e+03,4.515000e+03
mean,7.105427e-15,0.0,-3.619598e-17,-6.294952e-17,2.120627e-17,-7.604302e-15,3.776971e-17,1.017028e-16
std,0.000000e+00,0.0,1.000111e+00,1.000111e+00,1.000093e+00,1.000111e+00,1.000111e+00,1.000111e+00
min,7.105427e-15,0.0,-3.146406e+00,-3.250469e+00,-2.892146e-01,-2.096143e+00,-1.590811e+00,-1.678512e+00
25%,7.105427e-15,0.0,-7.648176e-01,-7.049471e-01,-2.892146e-01,-6.102985e-01,-7.305955e-01,-8.828946e-01
50%,7.105427e-15,0.0,7.041676e-02,-5.511481e-02,-2.892146e-01,1.326235e-01,1.296197e-01,2.638211e-02
75%,7.105427e-15,0.0,9.009695e-01,9.154946e-01,-2.892146e-01,8.755456e-01,9.898350e-01,8.219992e-01
max,7.105427e-15,0.0,1.738495e+00,1.910938e+00,1.287403e+01,1.618468e+00,1.563312e+00,1.731276e+00

In [24]:
required_cols = [
    "latitude",
    "longitude",
    "air_temperature",
    "dewpoint_temperature",
    "total_precipitation",
    "year",
    "month",
    "day",
    "soil_temperature",
    "soil_moisture",
]

final_scan_df = final_scan_df.dropna(subset=required_cols).copy()

print("Final SCAN shape after dropping nulls:", final_scan_df.shape)
print(final_scan_df[required_cols].isnull().sum())

Final SCAN shape after dropping nulls: (4515, 12)
latitude                0
longitude               0
air_temperature         0
dewpoint_temperature    0
total_precipitation     0
year                    0
month                   0
day                     0
soil_temperature        0
soil_moisture           0
dtype: int64

In [25]:
scan_train_df, scan_holdout_df = train_test_split(
    final_scan_df,
    test_size=0.10,
    random_state=42,
    shuffle=True
)

print("SCAN train shape:", scan_train_df.shape)
print("SCAN holdout shape:", scan_holdout_df.shape)

SCAN train shape: (4063, 12)
SCAN holdout shape: (452, 12)

In [26]:
final_scan_df.to_csv(PROCESSED_DIR / "scan_processed.csv", index=False)
scan_train_df.to_csv(PROCESSED_DIR / "scan_train.csv", index=False)
scan_holdout_df.to_csv(PROCESSED_DIR / "scan_holdout.csv", index=False)

print("✅ Saved:")
print(PROCESSED_DIR / "scan_processed.csv")
print(PROCESSED_DIR / "scan_train.csv")
print(PROCESSED_DIR / "scan_holdout.csv")

✅ Saved:
/Users/m.mughees/Desktop/Pi-515-2026/Data/SCAN/processed/scan_processed.csv
/Users/m.mughees/Desktop/Pi-515-2026/Data/SCAN/processed/scan_train.csv
/Users/m.mughees/Desktop/Pi-515-2026/Data/SCAN/processed/scan_holdout.csv

In [21]:

print(final_scan_df.columns.tolist())
final_scan_df.head()

['date', 'total_precipitation', 'air_temperature', 'dewpoint_temperature', 'soil_moisture', 'soil_temperature', 'year', 'month', 'day', 'latitude', 'longitude', 'source']

,date,total_precipitation,air_temperature,dewpoint_temperature,soil_moisture,soil_temperature,year,month,day,latitude,longitude,source
0,2010-10-12,0.0,19.711806,8.993056,0.281500,14.895833,2010.0,10.0,12.0,42.0347,-93.62,SCAN
1,2010-10-13,0.0,12.039352,-0.972222,0.278250,12.615741,2010.0,10.0,13.0,42.0347,-93.62,SCAN
2,2010-10-14,0.0,12.372685,-0.393519,0.275208,11.250000,2010.0,10.0,14.0,42.0347,-93.62,SCAN
3,2010-10-15,0.0,10.773148,1.273148,0.272708,11.018519,2010.0,10.0,15.0,42.0347,-93.62,SCAN
4,2010-10-16,0.0,13.719907,2.337963,0.272333,11.712963,2010.0,10.0,16.0,42.0347,-93.62,SCAN