In [20]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

In [21]:
BASE_DIR = Path.cwd().parents[1] if Path.cwd().name == "Data_Preparation" else Path.cwd()
DATA_DIR = BASE_DIR / "Data"

print("BASE_DIR:", BASE_DIR)
print("DATA_DIR exists:", DATA_DIR.exists())

BASE_DIR: /Users/m.mughees/Desktop/Pi-515-2026
DATA_DIR exists: True

In [22]:
train_df = pd.read_csv(DATA_DIR / "SMOS/train.csv")
test_df = pd.read_csv(DATA_DIR / "SMOS/test.csv")

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

train_df.head()

Train shape: (2099831, 26)
Test shape: (10000, 26)

,num__latitude,num__longitude,num__soil_temperature_level_1,num__total_precipitation,num__runoff,num__total_evaporation,num__potential_evaporation,num__2m_dewpoint_temperature,num__2m_temperature,num__snow_cover,...,cat__DistrictNa_Central,cat__DistrictNa_East Central,cat__DistrictNa_North Central,cat__DistrictNa_Northeast,cat__DistrictNa_Northwest,cat__DistrictNa_South Central,cat__DistrictNa_Southeast,cat__DistrictNa_Southwest,cat__DistrictNa_West Central,Soil_Moisture
0,-0.776986,1.426464,-1.369474,-0.367620,0.264376,1.097594,1.129800,-0.989945,-1.215082,0.768468,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.360234
1,-1.216539,0.035936,1.056937,-0.359515,0.063897,-0.850514,-0.224441,0.796616,0.823547,-0.269393,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.213469
2,-1.028159,1.205244,0.334309,-0.336933,-0.268701,-0.342088,0.007690,0.505021,0.467160,-0.269393,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.166913
3,0.478879,-0.912151,-0.674495,-0.368519,-0.352383,1.054375,0.972629,-0.400612,-0.537826,-0.265868,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.199984
4,-0.400226,0.035936,0.985257,-0.078794,0.318792,-1.182331,-0.441741,1.085233,0.926438,-0.269393,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.214700

In [23]:
rename_map = {
    "num__latitude": "latitude",
    "num__longitude": "longitude",
    "num__soil_temperature_level_1": "soil_temperature",
    "num__total_precipitation": "total_precipitation",
    "num__runoff": "runoff",
    "num__total_evaporation": "total_evaporation",
    "num__potential_evaporation": "potential_evaporation",
    "num__2m_dewpoint_temperature": "dewpoint_temperature",
    "num__2m_temperature": "air_temperature",
    "num__snow_cover": "snow_cover",
    "num__snow_depth": "snow_depth",
    "num__snowfall": "snowfall",
    "num__snowmelt": "snowmelt",
    "num__year": "year",
    "num__month": "month",
    "num__day": "day",
    "cat__DistrictNa_Central": "district_central",
    "cat__DistrictNa_East Central": "district_east_central",
    "cat__DistrictNa_North Central": "district_north_central",
    "cat__DistrictNa_Northeast": "district_northeast",
    "cat__DistrictNa_Northwest": "district_northwest",
    "cat__DistrictNa_South Central": "district_south_central",
    "cat__DistrictNa_Southeast": "district_southeast",
    "cat__DistrictNa_Southwest": "district_southwest",
    "cat__DistrictNa_West Central": "district_west_central",
    "Soil_Moisture": "soil_moisture",
}

In [24]:
train_df = train_df.rename(columns=rename_map)
test_df = test_df.rename(columns=rename_map)

train_df.head()

,latitude,longitude,soil_temperature,total_precipitation,runoff,total_evaporation,potential_evaporation,dewpoint_temperature,air_temperature,snow_cover,...,district_central,district_east_central,district_north_central,district_northeast,district_northwest,district_south_central,district_southeast,district_southwest,district_west_central,soil_moisture
0,-0.776986,1.426464,-1.369474,-0.367620,0.264376,1.097594,1.129800,-0.989945,-1.215082,0.768468,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.360234
1,-1.216539,0.035936,1.056937,-0.359515,0.063897,-0.850514,-0.224441,0.796616,0.823547,-0.269393,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.213469
2,-1.028159,1.205244,0.334309,-0.336933,-0.268701,-0.342088,0.007690,0.505021,0.467160,-0.269393,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.166913
3,0.478879,-0.912151,-0.674495,-0.368519,-0.352383,1.054375,0.972629,-0.400612,-0.537826,-0.265868,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.199984
4,-0.400226,0.035936,0.985257,-0.078794,0.318792,-1.182331,-0.441741,1.085233,0.926438,-0.269393,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.214700

In [25]:
features = [
    "latitude",
    "longitude",
    "air_temperature",
    "dewpoint_temperature",
    "total_precipitation",
    "month",
    "day",
    "year"
]

target = "soil_temperature"

In [26]:
X_full = train_df[features]
y_full = train_df[target]

X_train, X_dev, y_train, y_dev = train_test_split(
    X_full,
    y_full,
    test_size=0.2,
    random_state=42
)

X_test = test_df[features]
y_test = test_df[target]

print("X_train:", X_train.shape)
print("X_dev:", X_dev.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_dev:", y_dev.shape)
print("y_test:", y_test.shape)

X_train: (1679864, 8)
X_dev: (419967, 8)
X_test: (10000, 8)
y_train: (1679864,)
y_dev: (419967,)
y_test: (10000,)

In [27]:
X_train.head()

,latitude,longitude,air_temperature,dewpoint_temperature,total_precipitation,month,day,year
2034795,1.609158,-0.690931,-1.055888,-0.934288,-0.355161,1.322104,-1.437071,0.830305
1652062,-1.530505,0.257156,0.875412,1.089279,-0.000482,0.014939,-0.757728,0.830305
1638356,0.981226,-1.228180,-0.176975,0.243428,0.235831,0.995312,-1.550295,0.372430
2065790,-1.656092,0.035936,-0.505586,-0.196580,0.674606,1.322104,0.261287,-0.085444
887738,-1.404919,1.205244,-0.045009,-0.050305,-0.321858,-0.638644,0.034839,-0.314381

In [28]:
y_train.head()

2034795   -1.061143
1652062    0.938855
1638356   -0.140865
2065790   -0.550614
887738    -0.071779
Name: soil_temperature, dtype: float64

In [29]:
print("Final feature columns:")
print(X_train.columns.tolist())

print("\nShapes:")
print("X_train:", X_train.shape)
print("X_dev:", X_dev.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_dev:", y_dev.shape)
print("y_test:", y_test.shape)

Final feature columns:
['latitude', 'longitude', 'air_temperature', 'dewpoint_temperature', 'total_precipitation', 'month', 'day', 'year']

Shapes:
X_train: (1679864, 8)
X_dev: (419967, 8)
X_test: (10000, 8)
y_train: (1679864,)
y_dev: (419967,)
y_test: (10000,)

In [30]:
numeric_cols = [
    "latitude",
    "longitude",
    "air_temperature",
    "dewpoint_temperature",
    "total_precipitation",
    "year",
    "month",
    "day"
]

scaler = StandardScaler()
scaler.fit(X_train[numeric_cols])

joblib.dump(scaler, "../models/feature_scaler.joblib")

['../models/feature_scaler.joblib']